### ISSUE TITLE
There are the jar files that needed to make MVC and sessionFactory works

### ISSUE THREAD

**Issue by YixingCheng** [yyang325/YahooFinanceTradingSystem#12]
![image](https://cloud.githubusercontent.com/assets/4967016/13970992/0d095c84-f063-11e5-8445-82faea442e73.png)

**Comment by yyang325** [comment]
![image](https://cloud.githubusercontent.com/assets/7607839/14036553/4700c036-f210-11e5-8a7f-ac8f83c873d6.png)

Adding some new jar file, such as cglib-nodep-2.1_3

**Comment by yyang325** [comment]
refer to issue #24 
Close this issue
